### ISSUE TITLE
Middle pin on LED strip?

### ISSUE THREAD

**Issue by slowrobert** [torinmb/Alzheimers_Flashing_Gamma_Lights#2]
Hi, thank you for this.  I am completely new to Arduino.

You instructions say to connect to the middle pin of the LED strip.  When I look at the description online, it looks like the middle pin is +5v.  (https://www.adafruit.com/products/1138?gclid=CjwKEAiA4dPCBRCM4dqhlv2R1R8SJABom9pHnoW_rBo-baImYlb7MwPGUMsK0nUbw77FqXv4S-zN9xoCYFnw_wcB).  

Does this need two power supplies?  One for the arduino and one for the LED strip, or do you just tap into a 5v power supply prior to it going into the arduino to power the LED strip?  (5V 2A (2000mA) switching power supply - https://www.adafruit.com/products/276).

Also, the 10ms lag you noted, is this compensated for in the software?  I didn't see how it was implemented.   Do all of the LED flash at once or do they cascade with a 10ms delay between each?

Thanks.

**Comment by grennis** [comment]
@slowrobert Did you get this working, and if so can you share what is correct pin to connect and what power supplies were needed?

**Comment by torinmb** [comment]
@slowrobert depending on the LED strip the pin labeled 5v should go into the 5v pin on the Arduino. You won't need separate power for a strip with 60 LEDs, but if you would like to make them brighter you can purchase an external power supply. I filmed the strip with a slow motion camera and a timer in the background to make sure they were flashing at the correct timing and noticed the 10ms lag, which is corrected for in the Arduino code.
